name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sapmachine/lts
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $PATH
          java -version
