name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      springboot:
        image: nginx
        ports: 
          - 8080:80
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $PATH
          java -version
          curl localhost:8080
